---

- name: check list of running nodejs apps
  command: forever list
  register: forever_list
  changed_when: false

- name: stop nodejs app
  command: forever stop /var/www/web/server/index.js
  when: "forever_list.stdout.find('/var/www/web/server/index.js') != -1"
  become: false

- name: checkout repo
  git: repo=https://github.com/mitro/rtap.git
       dest=/var/www/web
       version=automate-deployment
       clone=no
  become: false

- name: install npm modules
  command: npm install
  args:
    chdir: /var/www/web

- name: run gulp
  command: gulp
  args:
    chdir: /var/www/web

- name: start nodejs app
  command: forever start -c babel-node /var/www/web/server/index.js
  become: false