---

- name: checkout repo
  git: repo=https://github.com/mitro/rtap.git
       dest={{ tmp_source_folder }}
       version=automate-deployment
  become: false

- name: check list of running nodejs apps
  command: forever list
  register: forever_list
  changed_when: false

- name: stop nodejs app
  command: forever stop {{ web_app_folder }}/server/index.js
  when: "forever_list.stdout.find('{{ web_app_folder }}/server/index.js') != -1"
  become: false

- name: (re)create app folfer
  command: mkdir -p {{ web_app_folder }}

- name: copy web app to app folder
  command: cp -a {{ tmp_source_folder }}/web {{ root_app_folder }}

- name: remove cloned git repo
  file: path={{ tmp_source_folder }}
        state=absent

- name: install npm modules
  command: npm install
  args:
    chdir: "{{ web_app_folder }}"

- name: run gulp
  command: gulp
  args:
    chdir: "{{ web_app_folder }}"

- name: start nodejs app
  command: forever start -c babel-node {{ web_app_folder }}/server/index.js
  become: false