
package kz.dtech.rt.ap.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IViolationGet", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IViolationGet {


    /**
     * 
     * @param parameters
     * @param userId
     * @return
     *     returns kz.dtech.rt.ap.ws.client.ArrayOfViolationGetWcfData
     */
    @WebMethod(operationName = "GetViolations", action = "http://tempuri.org/IViolationGet/GetViolations")
    @WebResult(name = "GetViolationsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetViolations", targetNamespace = "http://tempuri.org/", className = "kz.dtech.rt.ap.ws.client.GetViolations")
    @ResponseWrapper(localName = "GetViolationsResponse", targetNamespace = "http://tempuri.org/", className = "kz.dtech.rt.ap.ws.client.GetViolationsResponse")
    public ArrayOfViolationGetWcfData getViolations(
        @WebParam(name = "parameters", targetNamespace = "http://tempuri.org/")
        ViolationGetWcfParams parameters,
        @WebParam(name = "userId", targetNamespace = "http://tempuri.org/")
        Integer userId);

}
