
package kz.dtech.rt.ap.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ViolationGet", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://bdd-standnew.cloudapp.net:8000/ViolationGet.svc?singleWsdl")
public class ViolationGet
    extends Service
{

    private final static URL VIOLATIONGET_WSDL_LOCATION;
    private final static WebServiceException VIOLATIONGET_EXCEPTION;
    private final static QName VIOLATIONGET_QNAME = new QName("http://tempuri.org/", "ViolationGet");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://bdd-standnew.cloudapp.net:8000/ViolationGet.svc?singleWsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VIOLATIONGET_WSDL_LOCATION = url;
        VIOLATIONGET_EXCEPTION = e;
    }

    public ViolationGet() {
        super(__getWsdlLocation(), VIOLATIONGET_QNAME);
    }

    public ViolationGet(WebServiceFeature... features) {
        super(__getWsdlLocation(), VIOLATIONGET_QNAME, features);
    }

    public ViolationGet(URL wsdlLocation) {
        super(wsdlLocation, VIOLATIONGET_QNAME);
    }

    public ViolationGet(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VIOLATIONGET_QNAME, features);
    }

    public ViolationGet(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ViolationGet(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IViolationGet
     */
    @WebEndpoint(name = "BasicHttpBinding_IViolationGet")
    public IViolationGet getBasicHttpBindingIViolationGet() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IViolationGet"), IViolationGet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IViolationGet
     */
    @WebEndpoint(name = "BasicHttpBinding_IViolationGet")
    public IViolationGet getBasicHttpBindingIViolationGet(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IViolationGet"), IViolationGet.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VIOLATIONGET_EXCEPTION!= null) {
            throw VIOLATIONGET_EXCEPTION;
        }
        return VIOLATIONGET_WSDL_LOCATION;
    }

}
